### PR TITLE
System.sleep() wake up reason

### PR DESCRIPTION
**Pull request by avtolstoy**
<details>
  <summary><i>submission notes</i></summary>

```
**Important:** Please sanitize/remove any confidential info like usernames, passwords, org names, product names/ids, access tokens, client ids/secrets, or anything else you don't wish to share.

Please Read and Sign the Contributor License Agreement ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md)).

You may also delete this submission notes header if you'd like. Thank you for contributing!
```
</details>

**NOTE: Target branch is set to [feature/system-sleep-multiple-pins](https://github.com/spark/firmware/tree/feature/system-sleep-multiple-pins)**

### Problem

Users should be able to easily determine why the device woke up from STOP mode, especially after introduction of #1405 

### Solution

- All `System.sleep()` variants now return 
[`SleepResult`](https://github.com/spark/firmware/compare/feature/system-sleep-wkp-reason?expand=1#diff-9330b971deab5a41fa3008e5dea753f1R86) object that can be queried on the result of `System.sleep()` execution:
  - `WakeupReason SleepResult::reason();`
  - `bool SleepResult::wokenUpByRtc();`
  - `bool SleepResult::wokenUpByPin();`
  - `pin_t SleepResult::pin();`
  - `bool SleepResult::rtc();`
  - `system_error_t SleepResult::error();`
- A set of convenient functions was added to `System` class to retrieve information about the last sleep:
  - `WakeupReason System::wakeUpReason();`
  - `bool System::wokenUpByPin();`
  - `bool System::wokenUpByRtc();`
  - `pin_t System::wakeUpPin();`
  - `SleepResult System::sleepResult();`
  - `system_error_t System::sleepError();`
- `WakeupReason` is an enum of:
  - `WAKEUP_REASON_NONE = 0`
  - `WAKEUP_REASON_PIN = 1`
  - `WAKEUP_REASON_RTC = 2`
  - `WAKEUP_REASON_PIN_OR_RTC = 3`

### Steps to Test

- `wiring/api`
- `app/sleep_multiple_pins`

### Example App

See `app/sleep_multiple_pins`

### References

- #1405
- #1349
- [CH8894]

---

### Completeness

- [x] User is totes amazing for contributing!
- [x] Contributor has signed CLA ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md))
- [x] Problem and Solution clearly stated
- [ ] Run unit/integration/application tests on device
- [ ] **TODO:** Added documentation
- [ ] Added to CHANGELOG.md after merging (add links to docs and issues)

### CODE REVIEW

**Comment by pkourany** [comment]
@avtolstoy, this PR covers a STOP mode wake reason.  What about STANDBY (deep sleep) mode wake reason?

**Comment by avtolstoy** [comment]
@pkourany Currently the bootloader does not distinguish between being woken up by RTC or WKP pin (`RESET_REASON_POWER_MANAGEMENT`), so for STANDY mode the reason will be `WAKEUP_REASON_PIN_OR_RTC`.

**Comment by pkourany** [comment]
@avtolstoy, is the plan to update the bootloader at some point to distinguish the two?

**Comment by avtolstoy** [comment]
@pkourany It sure would be nice :) I'm not sure that we can do that though. As far as I remember, when waking up from STANDBY mode all the registers except for `PWR_CSR` are set to default values, and there is a single `WUF` bit in there that indicates there was a wakeup event either from WKP pin or from RTC:
image

**Comment by m-mcgowan** [comment]
For visibility, it looks like the conversation is resolved, so I will go ahead and merge this in for the upcoming 0.8.0-rc.2 release.

**Pull request merged**
