### PR TITLE
System.sleep(): support for multiple wake up pins

### LINKED ISSUE #1349: Support multiple pins to wake from System.sleep(wakeUpPin, edgeTriggerMode)
### References

[Docs - System.sleep()](https://docs.particle.io/reference/firmware/photon/#sleep-sleep-)

[waking-up-electron-from-sleep-using-pin-and-sms
](https://community.particle.io/t/waking-up-electron-from-sleep-using-pin-and-sms/32932/4)

---

## Feature/Enhancement Request

Add support for multiple (EXTI) interrupts/pins to wake Photon/Electron from `System.sleep(wakeUpPin, edgeTriggerMode)`.  Configuring an external (EXTI) interrupt via attachInterrupt() as per [note from @m-mcgowan](https://community.particle.io/t/photon-sleep-mode-wakeup-on-multiple-interrupts/15368/7) did not provide the (hoped for) additional pin wake functionality.

### PR DESCRIPTION
**Pull request by avtolstoy**
<details>
  <summary><i>submission notes</i></summary>

```
**Important:** Please sanitize/remove any confidential info like usernames, passwords, org names, product names/ids, access tokens, client ids/secrets, or anything else you don't wish to share.

Please Read and Sign the Contributor License Agreement ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md)).

You may also delete this submission notes header if you'd like. Thank you for contributing!
```
</details>

### Problem

Original issue #1349

### Solution

Implements the support in HAL, adds four additional `System.sleep()` variants:
- `System.sleep(std::initializer_list<pin_t>, InterruptMode, ...);`
- `System.sleep(std::initializer_list<pin_t>, std::initializer_list<InterruptMode>, ...);`
- `System.sleep(const pin_t*, size_t, InterruptMode, ...);`
- `System.sleep(const pin_t*, size_t, const InterruptMode*, size_t, ...);`

### Steps to Test

- `wiring/api`
- `app/sleep_multiple_pins`

### Example App

```c
void setup() {
}

void loop() {
  System.sleep({D0, D1}, RISING);
  System.sleep({D0, D1}, {RISING, FALLING});

  const pin_t pins[] = {D0, D1};
  const InterruptMode modes[] = {RISING, FALLING};
  System.sleep(pins, 2, RISING);
  System.sleep(pins, 2, modes, 2);
}
```

### References

- [CH8405]
- Closes #1349

---

### Completeness

**TODO: Add documentation**

- [x] User is totes amazing for contributing!
- [x] Contributor has signed CLA ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md))
- [x] Problem and Solution clearly stated
- [ ] Run unit/integration/application tests on device
- [ ] Added documentation
- [ ] Added to CHANGELOG.md after merging (add links to docs and issues)

### CODE REVIEW

**Comment by pkourany** [comment]
@avtolstoy, if I understand correctly, std::initializer_list<pin_t> uses dynamic allocation.  Using this a lot could lead to heap fragmentation.  If that is the case, perhaps the other forms of the function call are better.

**Comment by avtolstoy** [comment]
@pkourany It doesn't use dynamic allocations. `std::initializer_list<T>` is just a tiny convenient wrapper over a compiler-generated const array of elements. 

Curly-braced right-hand side of the expression is an initializer_list in both these cases as well:
- `const int test[] = {a, b, c, d};`
- `const int test[10] = {0};`

Having an `std::initializer_list<pin_t>` variant allows easy in-place passing of the pin identifiers, which sounds really convenient:
```c++
System.sleep({D0, D1, D2, D3, D4}, RISING);
System.sleep({D0, D1, D2, D3, D4}, {RISING, FALLING, RISING, FALLING, RISING});
```

Of course the PR includes `sleep(pin_t*, size_t, InterruptMode)` and `sleep(pin_t*, size_t, InterruptMode*, size_t)` variants for some advanced use cases.

**Comment by m-mcgowan** [comment]
I really like this, bravo!

**Comment by LouOtway** [comment]
Is there a way for application to know which pin caused the interrupt?

**Comment by avtolstoy** [comment]
@LouOtway Yeap, please take a look at #1410

**Pull request merged**
